import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode =
  | 'English'
  | 'हिन्दी'
  | 'অসমীয়া'
  | 'বাংলা'
  | 'ગુજરાતી'
  | 'ಕನ್ನಡ'
  | 'മലയാളം'
  | 'मराठी'
  | 'ଓଡ଼ିଆ'
  | 'ਪੰਜਾਬੀ'
  | 'தமிழ்'
  | 'తెలుగు'
  | 'اردو'
  | 'संस्कृतम्'
  | 'मैथिली'
  | 'ᱥᱟᱱᱛᱟᱲᱤ';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'English', label: 'English', nativeName: 'English' },
  { code: 'हिन्दी', label: 'Hindi', nativeName: 'हिंदी' },
  { code: 'অসমীয়া', label: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'বাংলা', label: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ગુજરાતી', label: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'ಕನ್ನಡ', label: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'മലയാളം', label: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'मराठी', label: 'Marathi', nativeName: 'मराठी' },
  { code: 'ଓଡ଼ିଆ', label: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'ਪੰਜਾਬੀ', label: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'தமிழ்', label: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'తెలుగు', label: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'اردو', label: 'Urdu', nativeName: 'اردو' },
  { code: 'संस्कृतम्', label: 'Sanskrit', nativeName: 'संस्कृत' },
  { code: 'मैथिली', label: 'Maithili', nativeName: 'मैथिली' },
  { code: 'ᱥᱟᱱᱛᱟᱲᱤ', label: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ' },
];

export type TranslationKey =
  | 'brand_name'
  | 'tagline'
  | 'nav_home'
  | 'nav_dos_donts'
  | 'nav_reports'
  | 'nav_map'
  | 'nav_incident'
  | 'nav_events'
  | 'nav_analytics'
  | 'nav_citizen'
  | 'nav_admin'
  | 'theme_bright'
  | 'theme_dark'
  | 'theme_mode'
  | 'role_citizen'
  | 'role_citizen_desc'
  | 'role_analyst'
  | 'role_analyst_desc'
  | 'role_admin'
  | 'role_admin_desc'
  | 'select_role'
  | 'language_select'
  | 'live_fresh'
  | 'syncing'
  | 'metric_active_clusters'
  | 'metric_active_sub'
  | 'metric_critical_alerts'
  | 'metric_critical_sub'
  | 'metric_states_affected'
  | 'metric_states_sub'
  | 'metric_trust_score'
  | 'metric_trust_sub'
  | 'filter_all'
  | 'filter_verified'
  | 'filter_critical'
  | 'filter_24h'
  | 'filter_label'
  | 'filter_active_label'
  | 'filter_reset'
  | 'map_title'
  | 'map_clusters'
  | 'layer_dark'
  | 'layer_satellite'
  | 'layer_verified'
  | 'feed_title'
  | 'feed_subtitle'
  | 'feed_verified'
  | 'feed_unverified'
  | 'feed_critical'
  | 'feed_details'
  | 'feed_no_reports'
  | 'alert_critical'
  | 'alert_post_x'
  | 'footer_text'
  | 'footer_crafted'
  | 'footer_sub';

const TRANSLATIONS: Record<LanguageCode, Record<TranslationKey, string>> = {
  English: {
    brand_name: 'VARSHANET',
    tagline: 'National Disaster Alert Portal & Radar',
    nav_home: 'Home',
    nav_dos_donts: "Do's & Don'ts",
    nav_reports: 'Reports',
    nav_map: 'Map',
    nav_incident: 'Incident Room',
    nav_events: 'Events',
    nav_analytics: 'Analytics',
    nav_citizen: 'Citizen Portal',
    nav_admin: 'Admin Ops',
    theme_bright: 'Bright',
    theme_dark: 'Dark',
    theme_mode: 'Theme Mode',
    role_citizen: 'Citizen',
    role_citizen_desc: 'Citizen Portal & Ground Reports',
    role_analyst: 'Analyst',
    role_analyst_desc: 'Disaster GIS Command & Forecaster',
    role_admin: 'Admin',
    role_admin_desc: 'NDMA Verification & System Ops',
    select_role: 'Select Operational Role',
    language_select: 'Language',
    live_fresh: 'Live Fresh',
    syncing: 'Syncing...',
    metric_active_clusters: 'Active Hazard Clusters',
    metric_active_sub: 'Corroborated incidents',
    metric_critical_alerts: 'Critical Red Warnings',
    metric_critical_sub: 'Severe emergency alerts',
    metric_states_affected: 'States Affected',
    metric_states_sub: 'Across Indian Union',
    metric_trust_score: 'Mean AI Trust',
    metric_trust_sub: 'Multi-factor score',
    filter_all: 'All Reports',
    filter_verified: 'Verified Only',
    filter_critical: 'Critical Red Alert',
    filter_24h: 'Past 24 Hours',
    filter_label: 'Dashboard GIS & Feed Filter:',
    filter_active_label: 'Active Filter:',
    filter_reset: 'Reset Filter',
    map_title: 'National Weather Radar',
    map_clusters: 'Clusters',
    layer_dark: 'Cyber Dark',
    layer_satellite: 'Satellite',
    layer_verified: 'Verified Reports',
    feed_title: 'Live Citizen & Official Weather Feed',
    feed_subtitle: 'Real-Time Crowdsourced & Automated Telemetry Stream',
    feed_verified: 'Verified',
    feed_unverified: 'Unverified',
    feed_critical: 'Critical Incident',
    feed_details: 'View Details',
    feed_no_reports: 'No reports matching current filter',
    alert_critical: 'CRITICAL',
    alert_post_x: 'Post to X',
    footer_text: 'VARSHANET 2.0 National Disaster Decision Support Grid | v2.0.0',
    footer_crafted: 'Crafted by Team Tech_Tonic',
    footer_sub: 'Ministry of Earth Sciences / IMD AI Impact Nowcasting & Citizen Response Protocol'
  },
  'हिन्दी': {
    brand_name: 'वर्षानेट',
    tagline: 'राष्ट्रीय आपदा चेतावनी पोर्टल एवं मौसम रडार',
    nav_home: 'होम',
    nav_dos_donts: 'क्या करें और क्या न करें',
    nav_reports: 'रिपोर्ट्स',
    nav_map: 'मानचित्र',
    nav_incident: 'आपदा नियंत्रण कक्ष',
    nav_events: 'आपदाएं',
    nav_analytics: 'एनालिटिक्स',
    nav_citizen: 'नागरिक पोर्टल',
    nav_admin: 'एडमिन ऑप्स',
    theme_bright: 'उजाला',
    theme_dark: 'डार्क',
    theme_mode: 'थीम मोड',
    role_citizen: 'नागरिक',
    role_citizen_desc: 'नागरिक पोर्टल एवं ग्राउंड रिपोर्ट',
    role_analyst: 'विश्लेषक',
    role_analyst_desc: 'आपदा जीआईएस कमांड एवं पूर्वानुमान',
    role_admin: 'प्रशासक',
    role_admin_desc: 'एनडीएमए सत्यापन एवं संचालन',
    select_role: 'परिचालन भूमिका चुनें',
    language_select: 'भाषा',
    live_fresh: 'लाइव अपडेट',
    syncing: 'सिंक हो रहा है...',
    metric_active_clusters: 'सक्रिय आपदा क्लस्टर',
    metric_active_sub: 'सत्यापित घटनाएं',
    metric_critical_alerts: 'गंभीर रेड अलर्ट',
    metric_critical_sub: 'आपातकालीन चेतावनियां',
    metric_states_affected: 'प्रभावित राज्य',
    metric_states_sub: 'अखिल भारतीय स्तर',
    metric_trust_score: 'औसत एआई विश्वास',
    metric_trust_sub: 'मल्टी-फैक्टर स्कोर',
    filter_all: 'सभी रिपोर्ट्स',
    filter_verified: 'केवल सत्यापित',
    filter_critical: 'गंभीर रेड अलर्ट',
    filter_24h: 'पिछले 24 घंटे',
    filter_label: 'डैशबोर्ड जीआईएस व फीड फिल्टर:',
    filter_active_label: 'सक्रिय फिल्टर:',
    filter_reset: 'फिल्टर रीसेट करें',
    map_title: 'राष्ट्रीय मौसम रडार',
    map_clusters: 'क्लस्टर्स',
    layer_dark: 'डार्क मैप',
    layer_satellite: 'सैटेलाइट',
    layer_verified: 'सत्यापित रिपोर्ट्स',
    feed_title: 'लाइव नागरिक एवं आधिकारिक मौसम फीड',
    feed_subtitle: 'रियल-टाइम क्राउडसोर्स्ड एवं स्वचालित टेलीमेट्री स्ट्रीम',
    feed_verified: 'सत्यापित',
    feed_unverified: 'असत्यापित',
    feed_critical: 'गंभीर आपदा',
    feed_details: 'विवरण देखें',
    feed_no_reports: 'कोई रिपोर्ट उपलब्ध नहीं है',
    alert_critical: 'गंभीर',
    alert_post_x: 'X पर साझा करें',
    footer_text: 'VARSHANET 2.0 राष्ट्रीय आपदा निर्णय समर्थन ग्रिड | v2.0.0',
    footer_crafted: 'टीम Tech_Tonic द्वारा निर्मित',
    footer_sub: 'पृथ्वी विज्ञान मंत्रालय / आईएमडी एआई इम्पैक्ट नाउकास्टिंग व नागरिक प्रोटोकॉल'
  },
  'বাংলা': {
    brand_name: 'বর্ষানেট',
    tagline: 'জাতীয় দুর্যোগ সতর্কতা পোর্টাল ও রাডার',
    nav_home: 'হোম',
    nav_dos_donts: 'করণীয় ও বর্জনীয়',
    nav_reports: 'রিপোর্ট',
    nav_map: 'মানচিত্র',
    nav_incident: 'কন্ট্রোল রুম',
    nav_events: 'ঘটনা',
    nav_analytics: 'বিশ্লেষণ',
    nav_citizen: 'নাগরিক পোর্টাল',
    nav_admin: 'অ্যাডমিন',
    theme_bright: 'উজ্জ্বল',
    theme_dark: 'ডার্ক',
    theme_mode: 'থিম মোড',
    role_citizen: 'নাগরিক',
    role_citizen_desc: 'নাগরিক পোর্টাল ও গ্রাউন্ড রিপোর্ট',
    role_analyst: 'বিশ্লেষক',
    role_analyst_desc: 'দুর্যোগ জিআইএস ও পূর্বাভাস',
    role_admin: 'অ্যাডমিন',
    role_admin_desc: 'এনডিএমএ যাচাই ও পরিচালনা',
    select_role: 'ভূমিকা নির্বাচন করুন',
    language_select: 'ভাষা',
    live_fresh: 'লাইভ আপডেট',
    syncing: 'সিঙ্ক হচ্ছে...',
    metric_active_clusters: 'সক্রিয় দুর্যোগ ক্লাস্টার',
    metric_active_sub: 'যাচাইকৃত ঘটনা',
    metric_critical_alerts: 'জরুরি রেড অ্যালার্ট',
    metric_critical_sub: 'জরুরি সতর্কতা',
    metric_states_affected: 'আক্রান্ত রাজ্য',
    metric_states_sub: 'সর্বভারতীয় তথ্য',
    metric_trust_score: 'এআই নির্ভুলতা স্কোর',
    metric_trust_sub: 'বহু-উৎস যাচাই',
    filter_all: 'সকল রিপোর্ট',
    filter_verified: 'যাচাইকৃত মাত্র',
    filter_critical: 'রেড অ্যালার্ট',
    filter_24h: 'গত ২৪ ঘণ্টা',
    filter_label: 'জিআইএস ও ফিড ফিল্টার:',
    filter_active_label: 'সক্রিয় ফিল্টার:',
    filter_reset: 'রিসেট করুন',
    map_title: 'জাতীয় আবহাওয়া রাডার',
    map_clusters: 'ক্লাস্টার',
    layer_dark: 'ডার্ক ম্যাপ',
    layer_satellite: 'স্যাটেলাইট',
    layer_verified: 'যাচাইকৃত রিপোর্ট',
    feed_title: 'লাইভ নাগরিক ও সরকারি আবহাওয়া ফিড',
    feed_subtitle: 'রিয়েল-টাইম তথ্য ও আবহাওয়া পূর্বাভাস',
    feed_verified: 'যাচাইকৃত',
    feed_unverified: 'অযাচাইকৃত',
    feed_critical: 'জরুরি ঘটনা',
    feed_details: 'বিস্তারিত দেখুন',
    feed_no_reports: 'কোনো রিপোর্ট পাওয়া যায়নি',
    alert_critical: 'জরুরি',
    alert_post_x: 'X এ পোস্ট করুন',
    footer_text: 'VARSHANET 2.0 জাতীয় দুর্যোগ সহায়তা গ্রিড | v2.0.0',
    footer_crafted: 'টিম Tech_Tonic দ্বারা নির্মিত',
    footer_sub: 'ভূবিজ্ঞান মন্ত্রক / আইএমডি এআই আবহাওয়া ও দুর্যোগ সতর্কতা প্রোটোকল'
  },
  'অসমীয়া': {
    brand_name: 'বৰ্ষানেট',
    tagline: 'ৰাষ্ট্ৰীয় দুৰ্যোগ সতৰ্কতা প’ৰ্টেল আৰু ৰাডাৰ',
    nav_home: 'গৃহ (হোম)',
    nav_dos_donts: 'কৰণীয় আৰু বৰ্জনীয়',
    nav_reports: 'প্ৰতিবেদন',
    nav_map: 'মানচিত্ৰ',
    nav_incident: 'নিয়ন্ত্ৰণ কক্ষ',
    nav_events: 'ঘটনাসমূহ',
    nav_analytics: 'বিশ্লেষণ',
    nav_citizen: 'নাগৰিক প’ৰ্টেল',
    nav_admin: 'এডমিন',
    theme_bright: 'উজ্বল',
    theme_dark: 'ডাৰ্ক',
    theme_mode: 'থিম মোড',
    role_citizen: 'নাগৰিক',
    role_citizen_desc: 'নাগৰিক প’ৰ্টেল আৰু তথ্য',
    role_analyst: 'বিশ্লেষক',
    role_analyst_desc: 'দুৰ্যোগ পৰ্যবেক্ষণ আৰু পূৰ্বানুমান',
    role_admin: 'প্ৰশাসক',
    role_admin_desc: 'এনডিএমএ অনুমোদন আৰু পৰিচালনা',
    select_role: 'ভূমিকা বাছক',
    language_select: 'ভাষা',
    live_fresh: 'লাইভ আপডেট',
    syncing: 'ছিংক হৈ আছে...',
    metric_active_clusters: 'সক্ৰিয় দুৰ্যোগ ক্লাষ্টাৰ',
    metric_active_sub: 'অনুমোদিত ঘটনাসমূহ',
    metric_critical_alerts: 'জৰুৰী ৰেড সতৰ্কবাৰ্তা',
    metric_critical_sub: 'জৰুৰী সতৰ্কতা',
    metric_states_affected: 'প্ৰভাৱিত ৰাজ্য',
    metric_states_sub: 'সৰ্বভাৰতীয় তথ্য',
    metric_trust_score: 'এআই বিশ্বাসযোগ্যতা',
    metric_trust_sub: 'বহু-উৎস নিৰ্ধাৰণ',
    filter_all: 'সকলো প্ৰতিবেদন',
    filter_verified: 'কেৱল অনুমোদিত',
    filter_critical: 'ৰেড সতৰ্কবাৰ্তা',
    filter_24h: 'বিগত ২৪ ঘণ্টা',
    filter_label: 'ফিল্টাৰ:',
    filter_active_label: 'সক্ৰিয় ফিল্টাৰ:',
    filter_reset: 'ৰিষ্ট কৰক',
    map_title: 'ৰাষ্ট্ৰীয় বতৰ ৰাডাৰ',
    map_clusters: 'ক্লাষ্টাৰসমূহ',
    layer_dark: 'ডাৰ্ক মেপ',
    layer_satellite: 'ছেটেলাইট',
    layer_verified: 'অনুমোদিত প্ৰতিবেদন',
    feed_title: 'লাইভ নাগৰিক আৰু বতৰ বাৰ্তা',
    feed_subtitle: 'প্ৰকৃত সময়ৰ দুৰ্যোগ তথ্য প্ৰৱাহ',
    feed_verified: 'অনুমোদিত',
    feed_unverified: 'অননুমোদিত',
    feed_critical: 'জৰুৰী দুৰ্যোগ',
    feed_details: 'বিৱৰণ চাওক',
    feed_no_reports: 'কোনো তথ্য পোৱা নগ’ল',
    alert_critical: 'জৰুৰী',
    alert_post_x: 'X লৈ পঠিয়াওক',
    footer_text: 'VARSHANET 2.0 ৰাষ্ট্ৰীয় দুৰ্যোগ সিদ্ধান্ত সমৰ্থন গ্ৰিড | v2.0.0',
    footer_crafted: 'টিম Tech_Tonic দ্বাৰা নিৰ্মিত',
    footer_sub: 'ভূ-বিজ্ঞান মন্ত্ৰালয় / আইএমডি এআই দুৰ্যোগ সতৰ্কতা প্ৰট’কল'
  },
  'ગુજરાતી': {
    brand_name: 'વર્ષાનેટ',
    tagline: 'રાષ્ટ્રીય આપત્તિ ચેતવણી પોર્ટલ અને રડાર',
    nav_home: 'હોમ',
    nav_dos_donts: 'શું કરવું અને શું ન કરવું',
    nav_reports: 'અહેવાલો',
    nav_map: 'નકશો',
    nav_incident: 'આપત્તિ કંટ્રોલ રૂમ',
    nav_events: 'ઘટનાઓ',
    nav_analytics: 'એનાલિટિક્સ',
    nav_citizen: 'નાગરિક પોર્ટલ',
    nav_admin: 'એડમિન',
    theme_bright: 'બ્રાઇટ',
    theme_dark: 'ડાર્ક',
    theme_mode: 'થીમ મોડ',
    role_citizen: 'નાગરિક',
    role_citizen_desc: 'નાગરિક પોર્ટલ અને ગ્રાઉન્ડ રિપોર્ટ્સ',
    role_analyst: 'વિશ્લેષક',
    role_analyst_desc: 'આપત્તિ GIS કમાન્ડ અને આગાહી',
    role_admin: 'વહીવટકર્તા',
    role_admin_desc: 'NDMA ચકાસણી અને સિસ્ટમ',
    select_role: 'ભૂમિકા પસંદ કરો',
    language_select: 'ભાષા',
    live_fresh: 'લાઈવ અપડેટ',
    syncing: 'સિંક થઈ રહ્યું છે...',
    metric_active_clusters: 'સક્રિય આપત્તિ ક્લસ્ટર્સ',
    metric_active_sub: 'ચકાસાયેલ ઘટનાઓ',
    metric_critical_alerts: 'ગંભીર રેડ એલર્ટ',
    metric_critical_sub: 'કટોકટી ચેતવણીઓ',
    metric_states_affected: 'અસરગ્રસ્ત રાજ્યો',
    metric_states_sub: 'સમગ્ર ભારત',
    metric_trust_score: 'સરેરાશ AI સ્કોર',
    metric_trust_sub: 'મલ્ટી-ફેક્ટર સ્કોર',
    filter_all: 'બધા અહેવાલો',
    filter_verified: 'માત્ર ચકાસાયેલ',
    filter_critical: 'રેડ એલર્ટ',
    filter_24h: 'છેલ્લા 24 કલાક',
    filter_label: 'ફિલ્ટર:',
    filter_active_label: 'સક્રિય ફિલ્ટર:',
    filter_reset: 'રીસેટ કરો',
    map_title: 'રાષ્ટ્રીય હવામાન રડાર',
    map_clusters: 'ક્લસ્ટર્સ',
    layer_dark: 'ડાર્ક નકશો',
    layer_satellite: 'સેટેલાઇટ',
    layer_verified: 'ચકાસાયેલ અહેવાલો',
    feed_title: 'લાઈવ નાગરિક અને હવામાન ફીડ',
    feed_subtitle: 'રીયલ-ટાઇમ માહિતી પ્રવાહ',
    feed_verified: 'ચકાસાયેલ',
    feed_unverified: 'અચકાસાયેલ',
    feed_critical: 'કટોકટી ઘટના',
    feed_details: 'વિગત જુઓ',
    feed_no_reports: 'કોઈ અહેવાલ ઉપલબ્ધ નથી',
    alert_critical: 'ગંભીર',
    alert_post_x: 'X પર શેર કરો',
    footer_text: 'VARSHANET 2.0 રાષ્ટ્રીય આપત્તિ નિર્ણય સહાય ગ્રીડ | v2.0.0',
    footer_crafted: 'ટીમ Tech_Tonic દ્વારા નિર્મિત',
    footer_sub: 'પૃથ્વી વિજ્ઞાન મંત્રાલય / IMD AI હવામાન અને આપત્તિ પ્રોટોકોલ'
  },
  'ಕನ್ನಡ': {
    brand_name: 'ವರ್ಷಾನೆಟ್',
    tagline: 'ರಾಷ್ಟ್ರೀಯ ವಿಪತ್ತು ಎಚ್ಚರಿಕೆ ಪೋರ್ಟಲ್ ಮತ್ತು ರೇಡಾರ್',
    nav_home: 'ಮುಖಪುಟ (Home)',
    nav_dos_donts: 'ಮಾಡಬೇಕಾದ ಮತ್ತು ಮಾಡಬಾರದ ಕೆಲಸಗಳು',
    nav_reports: 'ವರದಿಗಳು',
    nav_map: 'ನಕ್ಷೆ',
    nav_incident: 'ನಿಯಂತ್ರಣ ಕೊಠಡಿ',
    nav_events: 'ಘಟನೆಗಳು',
    nav_analytics: 'ವಿಶ್ಲೇಷಣೆ',
    nav_citizen: 'ನಾಗರಿಕ ಪೋರ್ಟಲ್',
    nav_admin: 'ಅಡ್ಮಿನ್',
    theme_bright: 'ಬ್ರೈಟ್',
    theme_dark: 'ಡಾರ್ಕ್',
    theme_mode: 'ಥೀಮ್ ಮೋಡ್',
    role_citizen: 'ನಾಗರಿಕ',
    role_citizen_desc: 'ನಾಗರಿಕ ಪೋರ್ಟಲ್ ಮತ್ತು ವರದಿಗಳು',
    role_analyst: 'ವಿಶ್ಲೇಷಕ',
    role_analyst_desc: 'ವಿಪತ್ತು ಕಮಾಂಡ್ ಮತ್ತು ಮುನ್ಸೂಚನೆ',
    role_admin: 'ನಿರ್ವಾಹಕ',
    role_admin_desc: 'NDMA ಪರಿಶೀಲನೆ ಮತ್ತು ನಿರ್ವಹಣೆ',
    select_role: 'ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    language_select: 'ಭಾಷೆ',
    live_fresh: 'ಲೈವ್ ಅಪ್‌ಡೇಟ್',
    syncing: 'ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...',
    metric_active_clusters: 'ಸಕ್ರಿಯ ವಿಪತ್ತು ಕ್ಲಸ್ಟರ್‌ಗಳು',
    metric_active_sub: 'ದೃಢಪಡಿಸಿದ ಘಟನೆಗಳು',
    metric_critical_alerts: 'ತೀವ್ರ ರೆಡ್ ಅಲರ್ಟ್',
    metric_critical_sub: 'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು',
    metric_states_affected: 'ಬಾಧಿತ ರಾಜ್ಯಗಳು',
    metric_states_sub: 'ಸಮಗ್ರ ಭಾರತ',
    metric_trust_score: 'AI ವಿಶ್ವಾಸಾರ್ಹತೆ',
    metric_trust_sub: 'ಬಹು-ಮೂಲ ಸ್ಕೋರ್',
    filter_all: 'ಎಲ್ಲಾ ವರದಿಗಳು',
    filter_verified: 'ದೃಢಪಡಿಸಿದವು ಮಾತ್ರ',
    filter_critical: 'ರೆಡ್ ಅಲರ್ಟ್',
    filter_24h: 'ಕಳೆದ 24 ಗಂಟೆಗಳು',
    filter_label: 'ಫಿಲ್ಟರ್:',
    filter_active_label: 'ಸಕ್ರಿಯ ಫಿಲ್ಟರ್:',
    filter_reset: 'ರೀಸೆಟ್ ಮಾಡಿ',
    map_title: 'ರಾಷ್ಟ್ರೀಯ ಹವಾಮಾನ ರೇಡಾರ್',
    map_clusters: 'ಕ್ಲಸ್ಟರ್‌ಗಳು',
    layer_dark: 'ಡಾರ್ಕ್ ಮ್ಯಾಪ್',
    layer_satellite: 'ಉಪಗ್ರಹ',
    layer_verified: 'ದೃಢೀಕೃತ ವರದಿಗಳು',
    feed_title: 'ಲೈವ್ ನಾಗರಿಕ ಮತ್ತು ಹವಾಮಾನ ಫೀಡ್',
    feed_subtitle: 'ನೈಜ-ಸಮಯದ ವಿಪತ್ತು ಮಾಹಿತಿ',
    feed_verified: 'ದೃಢೀಕೃತ',
    feed_unverified: 'ದೃಢೀಕರಿಸದ',
    feed_critical: 'ತುರ್ತು ಘಟನೆ',
    feed_details: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    feed_no_reports: 'ಯಾವುದೇ ವರದಿ ಲಭ್ಯವಿಲ್ಲ',
    alert_critical: 'ತುರ್ತು',
    alert_post_x: 'X ಗೆ ಪೋಸ್ಟ್ ಮಾಡಿ',
    footer_text: 'VARSHANET 2.0 ರಾಷ್ಟ್ರೀಯ ವಿಪತ್ತು ನಿರ್ಧಾರ ಬೆಂಬಲ ಗ್ರಿಡ್ | v2.0.0',
    footer_crafted: 'ಟೀಮ್ Tech_Tonic ನಿಂದ ನಿರ್ಮಿತ',
    footer_sub: 'ಭೂ ವಿಜ್ಞಾನ ಸಚಿವಾಲಯ / IMD AI ಹವಾಮಾನ ಮತ್ತು ವಿಪತ್ತು ಪ್ರೋಟೋಕಾಲ್'
  },
  'മലയാളം': {
    brand_name: 'വർഷാനെറ്റ്',
    tagline: 'ദേശീയ ദുരന്ത നിവാരണ പോർട്ടലും റഡാറും',
    nav_home: 'ഹോം',
    nav_dos_donts: 'ചെയ്യേണ്ടതും ചെയ്യരുതാത്തതും',
    nav_reports: 'റിപ്പോർട്ടുകൾ',
    nav_map: 'ഭൂപടം',
    nav_incident: 'കൺട്രോൾ റൂം',
    nav_events: 'ദുരന്തങ്ങൾ',
    nav_analytics: 'അനലിറ്റിക്സ്',
    nav_citizen: 'പൗര പോർട്ടൽ',
    nav_admin: 'അഡ്മിൻ',
    theme_bright: 'ബ്രൈറ്റ്',
    theme_dark: 'ഡാർക്ക്',
    theme_mode: 'തീം മോഡ്',
    role_citizen: 'പൗരൻ',
    role_citizen_desc: 'പൗര പോർട്ടലും റിപ്പോർട്ടുകളും',
    role_analyst: 'അനലിസ്റ്റ്',
    role_analyst_desc: 'ദുരന്ത നിരീക്ഷണവും പ്രവചനവും',
    role_admin: 'അഡ്മിൻ',
    role_admin_desc: 'NDMA സ്ഥിരീകരണവും നിയന്ത്രണവും',
    select_role: 'റോൾ തിരഞ്ഞെടുക്കുക',
    language_select: 'ഭാഷ',
    live_fresh: 'തത്സമയ അപ്‌ഡേറ്റ്',
    syncing: 'സമന്വയിപ്പിക്കുന്നു...',
    metric_active_clusters: 'സജീവ ദുരന്ത മേഖലകൾ',
    metric_active_sub: 'സ്ഥിരീകരിച്ച വിവരങ്ങൾ',
    metric_critical_alerts: 'റെഡ് അലർട്ട് ജാഗ്രത',
    metric_critical_sub: 'അടിയന്തര മുന്നറിയിപ്പുകൾ',
    metric_states_affected: 'ബാധിച്ച സംസ്ഥാനങ്ങൾ',
    metric_states_sub: 'ദേശീയ തലം',
    metric_trust_score: 'AI വിശ്വാസ്യത സ്കോർ',
    metric_trust_sub: 'മൾട്ടി-ഫാക്ടർ സ്കോർ',
    filter_all: 'എല്ലാ റിപ്പോർട്ടുകളും',
    filter_verified: 'സ്ഥിരീകരിച്ചവ മാത്രം',
    filter_critical: 'റെഡ് അലർട്ട്',
    filter_24h: 'കഴിഞ്ഞ 24 മണിക്കൂർ',
    filter_label: 'ഫിൽട്ടർ:',
    filter_active_label: 'സജീവ ഫിൽട്ടർ:',
    filter_reset: 'റീസെറ്റ് ചെയ്യുക',
    map_title: 'ദേശീയ കാലാവസ്ഥാ റഡാർ',
    map_clusters: 'മേഖലകൾ',
    layer_dark: 'ഡാർക്ക് മാപ്പ്',
    layer_satellite: 'ഉപഗ്രഹം',
    layer_verified: 'സ്ഥിരീകരിച്ച റിപ്പോർട്ടുകൾ',
    feed_title: 'തത്സമയ പൗര-കാലാവസ്ഥാ ഫീഡ്',
    feed_subtitle: 'തത്സമയ കാലാവസ്ഥാ വിവര പ്രവാഹം',
    feed_verified: 'സ്ഥിരീകരിച്ചത്',
    feed_unverified: 'സ്ഥിരീകരിക്കാത്തത്',
    feed_critical: 'അടിയന്തര സാഹചര്യം',
    feed_details: 'വിശദാംശങ്ങൾ കാണുക',
    feed_no_reports: 'റിപ്പോർട്ടുകൾ ഒന്നും ലഭ്യമല്ല',
    alert_critical: 'അതീവ ജാഗ്രത',
    alert_post_x: 'X-ൽ പങ്കിടുക',
    footer_text: 'VARSHANET 2.0 ദേശീയ ദുരന്ത നിവാരണ സഹായ ഗ്രിഡ് | v2.0.0',
    footer_crafted: 'ടീം Tech_Tonic നിർമ്മിച്ചത്',
    footer_sub: 'ഭൗമശാസ്ത്ര മന്ത്രാലയം / IMD AI കാലാവസ്ഥാ ദുരന്ത പ്രോട്ടോക്കോൾ'
  },
  'मराठी': {
    brand_name: 'वर्षानेट',
    tagline: 'राष्ट्रीय आपत्ती इशारा पोर्टल आणि हवामान रडार',
    nav_home: 'होम',
    nav_dos_donts: 'काय करावे आणि काय करू नये',
    nav_reports: 'अहवाल',
    nav_map: 'नकाशा',
    nav_incident: 'आपत्ती नियंत्रण कक्ष',
    nav_events: 'आपत्ती',
    nav_analytics: 'अॅनालिटिक्स',
    nav_citizen: 'नागरिक पोर्टल',
    nav_admin: 'अॅडमिन',
    theme_bright: 'उजेड',
    theme_dark: 'डार्क',
    theme_mode: 'थीम मोड',
    role_citizen: 'नागरिक',
    role_citizen_desc: 'नागरिक पोर्टल आणि ग्राउंड रिपोर्ट्स',
    role_analyst: 'विश्लेषक',
    role_analyst_desc: 'आपत्ती नियंत्रण आणि अंदाज',
    role_admin: 'प्रशासक',
    role_admin_desc: 'NDMA पडताळणी आणि प्रणाली',
    select_role: 'भूमिका निवडा',
    language_select: 'भाषा',
    live_fresh: 'थेट अद्यतन',
    syncing: 'सिंक होत आहे...',
    metric_active_clusters: 'सक्रिय आपत्ती क्लस्टर्स',
    metric_active_sub: 'पडताळणी केलेल्या घटना',
    metric_critical_alerts: 'गंभीर रेड अलर्ट',
    metric_critical_sub: 'आणीबाणी इशारे',
    metric_states_affected: 'प्रभावित राज्ये',
    metric_states_sub: 'अखिल भारतीय',
    metric_trust_score: 'सरासरी AI अचूकता',
    metric_trust_sub: 'मल्टी-फॅक्टर स्कोअर',
    filter_all: 'सर्व अहवाल',
    filter_verified: 'फक्त पडताळलेले',
    filter_critical: 'रेड अलर्ट',
    filter_24h: 'मागील २४ तास',
    filter_label: 'फिल्टर:',
    filter_active_label: 'सक्रिय फिल्टर:',
    filter_reset: 'रीसेट करा',
    map_title: 'राष्ट्रीय हवामान रडार',
    map_clusters: 'क्लस्टर्स',
    layer_dark: 'डार्क नकाशा',
    layer_satellite: 'सॅटेलाइट',
    layer_verified: 'पडताळलेले अहवाल',
    feed_title: 'थेट नागरिक आणि हवामान फीड',
    feed_subtitle: 'रिअल-टाइम आपत्ती माहिती प्रवाह',
    feed_verified: 'पडताळलेले',
    feed_unverified: 'अपडताळलेले',
    feed_critical: 'गंभीर घटना',
    feed_details: 'तपशील पहा',
    feed_no_reports: 'कोणताही अहवाल उपलब्ध नाही',
    alert_critical: 'गंभीर',
    alert_post_x: 'X वर शेअर करा',
    footer_text: 'VARSHANET 2.0 राष्ट्रीय आपत्ती निर्णय सहाय्य ग्रिड | v2.0.0',
    footer_crafted: 'टीम Tech_Tonic द्वारे निर्मित',
    footer_sub: 'पृथ्वी विज्ञान मंत्रालय / IMD AI हवामान आणि आपत्ती प्रोटोकॉल'
  },
  'ଓଡ଼ିଆ': {
    brand_name: 'ବର୍ଷାନେଟ୍',
    tagline: 'ଜାତୀୟ ବିପର୍ଯ୍ୟୟ ସତର୍କତା ପୋର୍ଟାଲ୍ ଏବଂ ରାଡାର୍',
    nav_home: 'ମୂଳପୃଷ୍ଠା (Home)',
    nav_dos_donts: 'କଣ କରିବେ ଏବଂ କଣ କରିବେ ନାହିଁ',
    nav_reports: 'ରିପୋର୍ଟ',
    nav_map: 'ମାନଚିତ୍ର',
    nav_incident: 'ନିୟନ୍ତ୍ରଣ କକ୍ଷ',
    nav_events: 'ଘଟଣାବଳୀ',
    nav_analytics: 'ବିଶ୍ଳେଷଣ',
    nav_citizen: 'ନାଗରିକ ପୋର୍ଟାଲ୍',
    nav_admin: 'ଆଡମିନ୍',
    theme_bright: 'ଉଜ୍ଜ୍ୱଳ',
    theme_dark: 'ଡାର୍କ',
    theme_mode: 'ଥିମ୍ ମୋଡ୍',
    role_citizen: 'ନାଗରିକ',
    role_citizen_desc: 'ନାଗରିକ ପୋର୍ଟାଲ୍ ଏବଂ ରିପୋର୍ଟ',
    role_analyst: 'ବିଶ୍ଳେଷକ',
    role_analyst_desc: 'ବିପର୍ଯ୍ୟୟ ନିରୀକ୍ଷଣ ଓ ପୂର୍ବାନୁମାନ',
    role_admin: 'ପ୍ରଶାସକ',
    role_admin_desc: 'NDMA ଯାଞ୍ଚ ଏବଂ ପରିଚାଳନା',
    select_role: 'ଭୂମିକା ଚୟନ କରନ୍ତୁ',
    language_select: 'ଭାଷା',
    live_fresh: 'ଲାଇଭ୍ ଅପଡେଟ୍',
    syncing: 'ସିଙ୍କ୍ ହେଉଛି...',
    metric_active_clusters: 'ସକ୍ରିୟ ବିପର୍ଯ୍ୟୟ କ୍ଲଷ୍ଟର୍',
    metric_active_sub: 'ପ୍ରମାଣିତ ଘଟଣାବଳୀ',
    metric_critical_alerts: 'ଜରୁରୀ ରେଡ୍ ଆଲର୍ଟ',
    metric_critical_sub: 'ଜରୁରୀକାଳୀନ ସତର୍କତା',
    metric_states_affected: 'ପ୍ରଭାବିତ ରାଜ୍ୟ',
    metric_states_sub: 'ସମଗ୍ର ଭାରତ',
    metric_trust_score: 'AI ବିଶ୍ୱସନୀୟତା',
    metric_trust_sub: 'ମଲ୍ଟି-ଫ୍ୟାକ୍ଟର୍ ସ୍କୋର',
    filter_all: 'ସମସ୍ତ ରିପୋର୍ଟ',
    filter_verified: 'କେବଳ ଯାଞ୍ଚ ହୋଇଥିବା',
    filter_critical: 'ରେଡ୍ ଆଲର୍ଟ',
    filter_24h: 'ଗତ ୨୪ ଘଣ୍ଟା',
    filter_label: 'ଫିଲ୍ଟର୍:',
    filter_active_label: 'ସକ୍ରିୟ ଫିଲ୍ଟର୍:',
    filter_reset: 'ରିସେଟ୍ କରନ୍ତୁ',
    map_title: 'ଜାତୀୟ ପାଣିପାଗ ରାଡାର୍',
    map_clusters: 'କ୍ଲଷ୍ଟର୍ ଗୁଡ଼ିକ',
    layer_dark: 'ଡାର୍କ ମ୍ୟାପ୍',
    layer_satellite: 'ସାଟେଲାଇଟ୍',
    layer_verified: 'ଯାଞ୍ଚ ହୋଇଥିବା ରିପୋର୍ଟ',
    feed_title: 'ଲାଇଭ୍ ନାଗରିକ ଏବଂ ପାଣିପାଗ ଫିଡ୍',
    feed_subtitle: 'ପ୍ରକୃତ ସମୟର ସୂଚନା ପ୍ରବାହ',
    feed_verified: 'ଯାଞ୍ଚିତ',
    feed_unverified: 'ଅଯାଞ୍ଚିତ',
    feed_critical: 'ଜରୁରୀ ବିପର୍ଯ୍ୟୟ',
    feed_details: 'ବିବରଣୀ ଦେଖନ୍ତୁ',
    feed_no_reports: 'କୌଣସି ରିପୋର୍ଟ ମିଳିଲା ନାହିଁ',
    alert_critical: 'ଜରୁରୀ',
    alert_post_x: 'X ରେ ସେୟାର୍ କରନ୍ତୁ',
    footer_text: 'VARSHANET 2.0 ଜାତୀୟ ବିପର୍ଯ୍ୟୟ ସହାୟତା ଗ୍ରିଡ୍ | v2.0.0',
    footer_crafted: 'ଟିମ୍ Tech_Tonic ଦ୍ୱାରା ନିର୍ମିତ',
    footer_sub: 'ଭୂବିଜ୍ଞାନ ମନ୍ତ୍ରଣାଳୟ / IMD AI ପାଣିପାଗ ଏବଂ ବିପର୍ଯ୍ୟୟ ପ୍ରୋଟୋକଲ୍'
  },
  'ਪੰਜਾਬੀ': {
    brand_name: 'ਵਰਸ਼ਾਨੈੱਟ',
    tagline: 'ਰਾਸ਼ਟਰੀ ਆਫ਼ਤ ਚੇਤਾਵਨੀ ਪੋਰਟਲ ਅਤੇ ਮੌਸਮ ਰਾਡਾਰ',
    nav_home: 'ਮੁੱਖ ਪੰਨਾ (Home)',
    nav_dos_donts: 'ਕੀ ਕਰਨਾ ਅਤੇ ਕੀ ਨਹੀਂ ਕਰਨਾ',
    nav_reports: 'ਰਿਪੋਰਟਾਂ',
    nav_map: 'ਨਕਸ਼ਾ',
    nav_incident: 'ਕੰਟਰੋਲ ਰੂਮ',
    nav_events: 'ਆਫ਼ਤਾਂ',
    nav_analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    nav_citizen: 'ਨਾਗਰਿਕ ਪੋਰਟਲ',
    nav_admin: 'ਐਡਮਿਨ',
    theme_bright: 'ਬਰਾਈਟ',
    theme_dark: 'ਡਾਰਕ',
    theme_mode: 'ਥੀਮ ਮੋਡ',
    role_citizen: 'ਨਾਗਰਿਕ',
    role_citizen_desc: 'ਨਾਗਰਿਕ ਪੋਰਟਲ ਅਤੇ ਰਿਪੋਰਟਾਂ',
    role_analyst: 'ਵਿਸ਼ਲੇਸ਼ਕ',
    role_analyst_desc: 'ਆਫ਼ਤ ਕਮਾਂਡ ਅਤੇ ਭਵਿੱਖਬਾਣੀ',
    role_admin: 'ਪ੍ਰਬੰਧਕ',
    role_admin_desc: 'NDMA ਪੜਤਾਲ ਅਤੇ ਪ੍ਰਣਾਲੀ',
    select_role: 'ਰੋਲ ਚੁਣੋ',
    language_select: 'ਭਾਸ਼ਾ',
    live_fresh: 'ਲਾਈਵ ਅੱਪਡੇਟ',
    syncing: 'ਸਿੰਕ ਹੋ ਰਿਹਾ ਹੈ...',
    metric_active_clusters: 'ਸਰਗਰਮ ਆਫ਼ਤ ਕਲੱਸਟਰ',
    metric_active_sub: 'ਪ੍ਰਮਾਣਿਤ ਘਟਨਾਵਾਂ',
    metric_critical_alerts: 'ਗੰਭੀਰ ਰੈੱਡ ਅਲਰਟ',
    metric_critical_sub: 'ਐਮਰਜੈਂਸੀ ਚੇਤਾਵਨੀਆਂ',
    metric_states_affected: 'ਪ੍ਰਭਾਵਿਤ ਰਾਜ',
    metric_states_sub: 'ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ',
    metric_trust_score: 'ਔਸਤ AI ਸਕੋਰ',
    metric_trust_sub: 'ਮਲਟੀ-ਫੈਕਟਰ ਸਕੋਰ',
    filter_all: 'ਸਾਰੀਆਂ ਰਿਪੋਰਟਾਂ',
    filter_verified: 'ਸਿਰਫ਼ ਪ੍ਰਮਾਣਿਤ',
    filter_critical: 'ਰੈੱਡ ਅਲਰਟ',
    filter_24h: 'ਪਿਛਲੇ 24 ਘੰਟੇ',
    filter_label: 'ਫਿਲਟਰ:',
    filter_active_label: 'ਸਰਗਰਮ ਫਿਲਟਰ:',
    filter_reset: 'ਰੀਸੈੱਟ ਕਰੋ',
    map_title: 'ਰਾਸ਼ਟਰੀ ਮੌਸਮ ਰਾਡਾਰ',
    map_clusters: 'ਕਲੱਸਟਰ',
    layer_dark: 'ਡਾਰਕ ਨਕਸ਼ਾ',
    layer_satellite: 'ਸੈਟੇਲਾਈਟ',
    layer_verified: 'ਪ੍ਰਮਾਣਿਤ ਰਿਪੋਰਟਾਂ',
    feed_title: 'ਲਾਈਵ ਨਾਗਰਿਕ ਅਤੇ ਮੌਸਮ ਫੀਡ',
    feed_subtitle: 'ਅਸਲ-ਸਮੇਂ ਦੀ ਆਫ਼ਤ ਜਾਣਕਾਰੀ',
    feed_verified: 'ਪ੍ਰਮਾਣਿਤ',
    feed_unverified: 'ਗੈਰ-ਪ੍ਰਮਾਣਿਤ',
    feed_critical: 'ਗੰਭੀਰ ਘਟਨਾ',
    feed_details: 'ਵੇਰਵੇ ਦੇਖੋ',
    feed_no_reports: 'ਕੋਈ ਰਿਪੋਰਟ ਉਪਲਬਧ ਨਹੀਂ',
    alert_critical: 'ਗੰਭੀਰ',
    alert_post_x: 'X ਤੇ ਸਾਂਝਾ ਕਰੋ',
    footer_text: 'VARSHANET 2.0 ਰਾਸ਼ਟਰੀ ਆਫ਼ਤ ਸਹਾਇਤਾ ਗਰਿੱਡ | v2.0.0',
    footer_crafted: 'ਟੀਮ Tech_Tonic ਦੁਆਰਾ ਤਿਆਰ ਕੀਤਾ ਗਿਆ',
    footer_sub: 'ਧਰਤੀ ਵਿਗਿਆਨ ਮੰਤਰਾਲਾ / IMD AI ਮੌਸਮ ਅਤੇ ਆਫ਼ਤ ਪ੍ਰੋਟੋਕੋਲ'
  },
  'தமிழ்': {
    brand_name: 'வர்ஷாநெட்',
    tagline: 'தேசிய பேரிடர் எச்சரிக்கை தளம் மற்றும் ரேடார்',
    nav_home: 'முகப்பு (Home)',
    nav_dos_donts: 'செய்ய வேண்டியவை மற்றும் செய்யக்கூடாதவை',
    nav_reports: 'அறிக்கைகள்',
    nav_map: 'வரைபடம்',
    nav_incident: 'கட்டுப்பாட்டு அறை',
    nav_events: 'பேரிடர்கள்',
    nav_analytics: 'பகுப்பாய்வு',
    nav_citizen: 'குடிமக்கள் தளம்',
    nav_admin: 'நிர்வாகி',
    theme_bright: 'வெளிச்சம்',
    theme_dark: 'இருள்',
    theme_mode: 'தீம் முறை',
    role_citizen: 'குடிமகன்',
    role_citizen_desc: 'குடிமக்கள் தளம் மற்றும் கள அறிக்கைகள்',
    role_analyst: 'பகுப்பாய்வாளர்',
    role_analyst_desc: 'பேரிடர் கண்காணிப்பு மற்றும் முன்னறிவிப்பு',
    role_admin: 'நிர்வாகி',
    role_admin_desc: 'NDMA சரிபார்ப்பு மற்றும் இயக்கம்',
    select_role: 'பங்கைத் தேர்ந்தெடுக்கவும்',
    language_select: 'மொழி',
    live_fresh: 'நேரலை புதுப்பிப்பு',
    syncing: 'ஒத்திசைக்கிறது...',
    metric_active_clusters: 'செயலில் உள்ள பேரிடர் மண்டலங்கள்',
    metric_active_sub: 'சரிபார்க்கப்பட்ட நிகழ்வுகள்',
    metric_critical_alerts: 'ரெட் அலர்ட் எச்சரிக்கைகள்',
    metric_critical_sub: 'அவசர எச்சரிக்கைகள்',
    metric_states_affected: 'பாதிக்கப்பட்ட மாநிலங்கள்',
    metric_states_sub: 'இந்தியா முழுவதும்',
    metric_trust_score: 'AI நம்பகத்தன்மை',
    metric_trust_sub: 'பன்முக மதிப்பீடு',
    filter_all: 'அனைத்து அறிக்கைகள்',
    filter_verified: 'சரிபார்க்கப்பட்டவை மட்டும்',
    filter_critical: 'ரெட் அலர்ட்',
    filter_24h: 'கடந்த 24 மணிநேரம்',
    filter_label: 'வடிகட்டி:',
    filter_active_label: 'செயலில் உள்ள வடிகட்டி:',
    filter_reset: 'மீட்டமைக்கவும்',
    map_title: 'தேசிய வானிலை ரேடார்',
    map_clusters: 'மண்டலங்கள்',
    layer_dark: 'டார்க் மேப்',
    layer_satellite: 'செயற்கைக்கோள்',
    layer_verified: 'சரிபார்க்கப்பட்ட அறிக்கைகள்',
    feed_title: 'நேரலை குடிமக்கள் மற்றும் வானிலை தகவல்',
    feed_subtitle: 'உடனடி பேரிடர் தகவல் ஓட்டம்',
    feed_verified: 'சரிபார்க்கப்பட்டது',
    feed_unverified: 'சரிபார்க்கப்படாதது',
    feed_critical: 'அவசர பேரிடர்',
    feed_details: 'விவரங்களைக் காண்க',
    feed_no_reports: 'அறிக்கைகள் எதுவும் இல்லை',
    alert_critical: 'அவசரம்',
    alert_post_x: 'X-ல் பகிரவும்',
    footer_text: 'VARSHANET 2.0 தேசிய பேரிடர் முடிவு ஆதரவு கட்டமைப்பு | v2.0.0',
    footer_crafted: 'டீம் Tech_Tonic உருவாக்கியது',
    footer_sub: 'புவி அறிவியல் அமைச்சகம் / IMD AI வானிலை மற்றும் பேரிடர் நெறிமுறை'
  },
  'తెలుగు': {
    brand_name: 'వర్షానెట్',
    tagline: 'జాతీయ విపత్తు హెచ్చరిక పోర్టల్ మరియు రాడార్',
    nav_home: 'హోమ్ (Home)',
    nav_dos_donts: 'చేయవలసినవి మరియు చేయకూడనివి',
    nav_reports: 'నివేదికలు',
    nav_map: 'మ్యాప్',
    nav_incident: 'కంట్రోల్ రూమ్',
    nav_events: 'విపత్తులు',
    nav_analytics: 'విశ్లేషణ',
    nav_citizen: 'పౌర పోర్టల్',
    nav_admin: 'అడ్మిన్',
    theme_bright: 'బ్రైట్',
    theme_dark: 'డార్క్',
    theme_mode: 'థీమ్ మోడ్',
    role_citizen: 'పౌరుడు',
    role_citizen_desc: 'పౌర పోర్టల్ మరియు నివేదికలు',
    role_analyst: 'విశ్లేషకుడు',
    role_analyst_desc: 'విపత్తు కమాండ్ మరియు అంచనా',
    role_admin: 'నిర్వాహకుడు',
    role_admin_desc: 'NDMA ధృవీకరణ మరియు నిర్వహణ',
    select_role: 'పాత్రను ఎంచుకోండి',
    language_select: 'భాష',
    live_fresh: 'లైవ్ అప్‌డేట్',
    syncing: 'సింక్ అవుతోంది...',
    metric_active_clusters: 'క్రియాశీల విపత్తు క్లస్టర్లు',
    metric_active_sub: 'ధృవీకరించబడిన సంఘటనలు',
    metric_critical_alerts: 'రెడ్ అలర్ట్ హెచ్చరికలు',
    metric_critical_sub: 'అత్యవసర హెచ్చరికలు',
    metric_states_affected: 'ప్రభావిత రాష్ట్రాలు',
    metric_states_sub: 'భారతదేశ వ్యాప్తంగా',
    metric_trust_score: 'AI విశ్వసనీయత స్కోరు',
    metric_trust_sub: 'బహుళ-కారకాల స్కోర్',
    filter_all: 'అన్ని నివేదికలు',
    filter_verified: 'ధృవీకరించబడినవి మాత్రమే',
    filter_critical: 'రెడ్ అలర్ట్',
    filter_24h: 'గత 24 గంటలు',
    filter_label: 'ఫిల్టర్:',
    filter_active_label: 'యాక్టివ్ ఫిల్టర్:',
    filter_reset: 'రీసెట్ చేయండి',
    map_title: 'జాతీయ వాతావరణ రాడార్',
    map_clusters: 'క్లస్టర్లు',
    layer_dark: 'డార్క్ మ్యాప్',
    layer_satellite: 'ఉపగ్రహం',
    layer_verified: 'ధృవీకరించిన నివేదికలు',
    feed_title: 'లైవ్ పౌర మరియు వాతావరణ ఫీడ్',
    feed_subtitle: 'రియల్-టైమ్ సమాచార ప్రవాహం',
    feed_verified: 'ధృవీకరించబడింది',
    feed_unverified: 'ధృవీకరించబడనిది',
    feed_critical: 'అత్యవసర విపత్తు',
    feed_details: 'వివరాలు చూడండి',
    feed_no_reports: 'నివేదికలు ఏవీ అందుబాటులో లేవు',
    alert_critical: 'అత్యవసరం',
    alert_post_x: 'X లో పోస్ట్ చేయండి',
    footer_text: 'VARSHANET 2.0 జాతీయ విపత్తు నిర్ణయ మద్దతు గ్రిడ్ | v2.0.0',
    footer_crafted: 'టీమ్ Tech_Tonic చే రూపొందించబడింది',
    footer_sub: 'భూ విజ్ఞాన మంత్రిత్వ శాఖ / IMD AI వాతావరణ మరియు విపత్తు ప్రోటోకాల్'
  },
  'اردو': {
    brand_name: 'ورشانٹ',
    tagline: 'قومی ڈیزاسٹر الرٹ پورٹل اور ریڈار',
    nav_home: 'ہوم (Home)',
    nav_dos_donts: 'کیا کریں اور کیا نہ کریں',
    nav_reports: 'رپورٹس',
    nav_map: 'نقشہ',
    nav_incident: 'کنٹرول روم',
    nav_events: 'واقعات',
    nav_analytics: 'تجزیات',
    nav_citizen: 'شہری پورٹل',
    nav_admin: 'ایڈمن',
    theme_bright: 'روشن',
    theme_dark: 'ڈارک',
    theme_mode: 'تھیم موڈ',
    role_citizen: 'شہری',
    role_citizen_desc: 'شہری پورٹل اور زمینی رپورٹس',
    role_analyst: 'تجزیہ کار',
    role_analyst_desc: 'ڈیزاسٹر کمانڈ اور پیش گوئی',
    role_admin: 'منتظم',
    role_admin_desc: 'NDMA تصدیق اور آپریشنز',
    select_role: 'کردار منتخب کریں',
    language_select: 'زبان',
    live_fresh: 'تازہ ترین لائیو',
    syncing: 'ہم آہنگ ہو رہا ہے...',
    metric_active_clusters: 'فعال خطرے کے کلسٹرز',
    metric_active_sub: 'تصدیق شدہ واقعات',
    metric_critical_alerts: 'ریڈ الرٹ وارننگز',
    metric_critical_sub: 'ہنگامی انتباہات',
    metric_states_affected: 'متاثرہ ریاستیں',
    metric_states_sub: 'پورے بھارت میں',
    metric_trust_score: 'AI اعتماد سکور',
    metric_trust_sub: 'کثیر جہتی سکور',
    filter_all: 'تمام رپورٹس',
    filter_verified: 'صرف تصدیق شدہ',
    filter_critical: 'ریڈ الرٹ',
    filter_24h: 'گزشتہ 24 گھنٹے',
    filter_label: 'فلٹر:',
    filter_active_label: 'فعال فلٹر:',
    filter_reset: 'دوبارہ ترتیب دیں',
    map_title: 'قومی موسمیاتی ریڈار',
    map_clusters: 'کلسٹرز',
    layer_dark: 'ڈارک نقشہ',
    layer_satellite: 'سیٹلائٹ',
    layer_verified: 'تصدیق شدہ رپورٹس',
    feed_title: 'لائیو شہری اور موسمیاتی فیڈ',
    feed_subtitle: 'حقیقی وقت کا معلوماتی سلسلہ',
    feed_verified: 'تصدیق شدہ',
    feed_unverified: 'غیر تصدیق شدہ',
    feed_critical: 'ہنگامی واقعہ',
    feed_details: 'تفصیلات دیکھیں',
    feed_no_reports: 'کوئی رپورٹ دستیاب نہیں ہے',
    alert_critical: 'انتہائی اہم',
    alert_post_x: 'X پر شیئر کریں',
    footer_text: 'VARSHANET 2.0 نیشنل ڈیزاسٹر سپورٹ گرڈ | v2.0.0',
    footer_crafted: 'ٹیم Tech_Tonic کی طرف سے تیار کردہ',
    footer_sub: 'وزارت ارتھ سائنسز / IMD AI موسمیاتی و آفات کا پروٹوکول'
  },
  'संस्कृतम्': {
    brand_name: 'वर्षामार्ग:',
    tagline: 'राष्ट्रीय आपदा सूचना पटलम् तथा रडार',
    nav_home: 'गृहम् (Home)',
    nav_dos_donts: 'कर्तव्यम् अकर्तव्यम् च',
    nav_reports: 'वृत्तान्ताः',
    nav_map: 'मानचित्रम्',
    nav_incident: 'नियन्त्रणकक्षः',
    nav_events: 'आपदः',
    nav_analytics: 'विश्लेषणम्',
    nav_citizen: 'नागरिकपटलम्',
    nav_admin: 'प्रशासकः',
    theme_bright: 'प्रकाशः',
    theme_dark: 'अन्धकारः',
    theme_mode: 'वर्णक्रमः',
    role_citizen: 'नागरिकः',
    role_citizen_desc: 'नागरिकपटलम् प्रत्यक्षवृत्तान्ताश्च',
    role_analyst: 'विश्लेषकः',
    role_analyst_desc: 'आपदा पूर्वानुमानम् नियन्त्रणञ्च',
    role_admin: 'प्रशासकः',
    role_admin_desc: 'एनडीएमए प्रमाणीकरणम्',
    select_role: 'भूमिकां वृणुध्वम्',
    language_select: 'भाषा',
    live_fresh: 'सद्यस्तनम्',
    syncing: 'समन्वयनं क्रियते...',
    metric_active_clusters: 'सक्रियापद्समूहाः',
    metric_active_sub: 'प्रमाणीकृता आपदः',
    metric_critical_alerts: 'गम्भीराः सूचनाः',
    metric_critical_sub: 'आत्ययिकचेतावनानि',
    metric_states_affected: 'प्रभावितानि राज्यानि',
    metric_states_sub: 'समग्रभारते',
    metric_trust_score: 'एआई सत्यताङ्कः',
    metric_trust_sub: 'बहुपक्षीयमानम्',
    filter_all: 'सर्वे वृत्तान्ताः',
    filter_verified: 'केवलं प्रमाणीकृतम्',
    filter_critical: 'रक्तचेतावनी',
    filter_24h: 'विगताः २४ होराः',
    filter_label: 'शोधनी:',
    filter_active_label: 'सक्रिया शोधनी:',
    filter_reset: 'पुनः स्थापयतु',
    map_title: 'राष्ट्रीय मौसम रडार',
    map_clusters: 'समूहाः',
    layer_dark: 'श्यामचित्रम्',
    layer_satellite: 'उपग्रहचित्रम्',
    layer_verified: 'प्रमाणीकृतवृत्तान्ताः',
    feed_title: 'प्रत्यक्षं नागरिक-मौसम-प्रवाहः',
    feed_subtitle: 'यथार्थकालिक-सूचना-प्रवाहः',
    feed_verified: 'प्रमाणीकृतम्',
    feed_unverified: 'अप्रमाणीकृतम्',
    feed_critical: 'आत्ययिकी घटना',
    feed_details: 'विवरणं पश्यतु',
    feed_no_reports: 'वृत्तान्तः न लब्धः',
    alert_critical: 'आत्ययिकम्',
    alert_post_x: 'X इत्यत्र प्रेषयतु',
    footer_text: 'VARSHANET 2.0 राष्ट्रियापदा निर्णयसहायतापटलम् | v2.0.0',
    footer_crafted: 'दल Tech_Tonic द्वारा निर्मितम्',
    footer_sub: 'पृथ्वीविज्ञानमन्त्रालयः / आईएमडी एआई मौसमप्रोटोकॉल'
  },
  'मैथिली': {
    brand_name: 'वर्षानेट',
    tagline: 'राष्ट्रीय आपदा चेतावनी पोर्टल आ रडार',
    nav_home: 'गृह (Home)',
    nav_dos_donts: 'की करू आ की नहि करू',
    nav_reports: 'रिपोर्ट',
    nav_map: 'नक्शा',
    nav_incident: 'नियंत्रण कक्ष',
    nav_events: 'घटना सभ',
    nav_analytics: 'विश्लेषण',
    nav_citizen: 'नागरिक पोर्टल',
    nav_admin: 'एडमिन',
    theme_bright: 'उज्जर',
    theme_dark: 'करिया',
    theme_mode: 'थीम मोड',
    role_citizen: 'नागरिक',
    role_citizen_desc: 'नागरिक पोर्टल आ जमीनी रिपोर्ट',
    role_analyst: 'विश्लेषक',
    role_analyst_desc: 'आपदा कमान आ भविष्यवाणी',
    role_admin: 'प्रशासक',
    role_admin_desc: 'NDMA सत्यापन आ प्रबंधन',
    select_role: 'भूमिका चुनू',
    language_select: 'भाषा',
    live_fresh: 'ताजा अपडेट',
    syncing: 'सिंक भऽ रहल अछि...',
    metric_active_clusters: 'सक्रिय आपदा समूह',
    metric_active_sub: 'सत्यापित घटना',
    metric_critical_alerts: 'गंभीर लाल चेतावनी',
    metric_critical_sub: 'आपातकालीन सूचना',
    metric_states_affected: 'प्रभावित राज्य',
    metric_states_sub: 'अखिल भारतीय',
    metric_trust_score: 'AI विश्वसनीयता स्कोर',
    metric_trust_sub: 'सटीक गणना',
    filter_all: 'सब रिपोर्ट',
    filter_verified: 'मात्र सत्यापित',
    filter_critical: 'लाल चेतावनी',
    filter_24h: 'बीतल २४ घंटा',
    filter_label: 'फिल्टर:',
    filter_active_label: 'सक्रिय फिल्टर:',
    filter_reset: 'रीसेट करू',
    map_title: 'राष्ट्रीय मौसम रडार',
    map_clusters: 'क्लस्टर्स',
    layer_dark: 'डार्क मैप',
    layer_satellite: 'सैटेलाइट',
    layer_verified: 'सत्यापित रिपोर्ट सभ',
    feed_title: 'लाइव नागरिक आ मौसम फीड',
    feed_subtitle: 'रियल-टाइम आपदा सूचना प्रवाह',
    feed_verified: 'सत्यापित',
    feed_unverified: 'असत्यापित',
    feed_critical: 'गंभीर आपदा',
    feed_details: 'विवरण देखू',
    feed_no_reports: 'कोनो रिपोर्ट उपलब्ध नहि अछि',
    alert_critical: 'गंभीर',
    alert_post_x: 'X पर साझा करू',
    footer_text: 'VARSHANET 2.0 राष्ट्रीय आपदा निर्णय समर्थन ग्रिड | v2.0.0',
    footer_crafted: 'टीम Tech_Tonic द्वारा निर्मित',
    footer_sub: 'पृथ्वी विज्ञान मंत्रालय / IMD AI मौसम आ आपदा प्रोटोकॉल'
  },
  'ᱥᱟᱱᱛᱟᱲᱤ': {
    brand_name: 'ᱵᱟᱨᱥᱟᱱᱮᱴ',
    tagline: 'ᱡᱟᱹᱛᱤᱭᱟᱹᱨᱤ ᱟᱯᱚᱛ ᱦᱩᱥᱤᱭᱟᱹᱨ ᱯᱚᱨᱴᱟᱞ ᱟᱨ ᱨᱟᱰᱟᱨ',
    nav_home: 'ᱚᱲᱟᱜ (Home)',
    nav_dos_donts: 'ᱪᱮᱫ ᱠᱟᱹᱢᱤ ᱟᱨ ᱪᱮᱫ ᱵᱟᱝ',
    nav_reports: 'ᱨᱤᱯᱳᱨᱴ',
    nav_map: 'ᱢᱮᱯ',
    nav_incident: 'ᱠᱚᱱᱴᱨᱳᱞ ᱨᱩᱢ',
    nav_events: 'ᱜᱷᱚᱴᱚᱱ',
    nav_analytics: 'ᱮᱱᱟᱞᱤᱴᱤᱠᱥ',
    nav_citizen: 'ᱱᱟᱹᱜᱟᱹᱨᱤᱭᱟᱹ ᱯᱚᱨᱴᱟᱞ',
    nav_admin: 'ᱮᱰᱢᱤᱱ',
    theme_bright: 'ᱢᱟᱨᱥᱟᱞ',
    theme_dark: 'ᱧᱩᱛ',
    theme_mode: 'ᱛᱷᱤᱢ',
    role_citizen: 'ᱱᱟᱹᱜᱟᱹᱨᱤᱭᱟᱹ',
    role_citizen_desc: 'ᱱᱟᱹᱜᱟᱹᱨᱤᱭᱟᱹ ᱯᱚᱨᱴᱟᱞ ᱟᱨ ᱨᱤᱯᱳᱨᱴ',
    role_analyst: 'ᱮᱱᱟᱞᱤᱥᱴ',
    role_analyst_desc: 'ᱟᱯᱚᱛ ᱧᱮᱞ ᱟᱨ ᱞᱟᱦᱟ ᱞᱟᱹᱭ',
    role_admin: 'ᱮᱰᱢᱤᱱ',
    role_admin_desc: 'NDMA ᱯᱟᱹᱛᱭᱟᱹᱣ ᱟᱨ ᱪᱟᱪᱞᱟᱣ',
    select_role: 'ᱨᱳᱞ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
    language_select: 'ᱯᱟᱹᱨᱥᱤ',
    live_fresh: 'ᱞᱟᱭᱤᱵᱽ ᱱᱟᱣᱟ',
    syncing: 'ᱥᱤᱝᱠ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...',
    metric_active_clusters: 'ᱮᱠᱴᱤᱵᱷ ᱟᱯᱚᱛ ᱠᱞᱟᱥᱴᱟᱨ',
    metric_active_sub: 'ᱯᱟᱹᱛᱭᱟᱹᱣ ᱟᱠᱟᱱ ᱜᱷᱚᱴᱚᱱ',
    metric_critical_alerts: 'ᱟᱨᱟᱜ ᱦᱩᱥᱤᱭᱟᱹᱨ',
    metric_critical_sub: 'ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱦᱩᱥᱤᱭᱟᱹᱨ',
    metric_states_affected: 'ᱚᱨᱥᱚᱝ ᱯᱚᱱᱚᱛ',
    metric_states_sub: 'ᱥᱤᱧᱚᱛ ᱡᱟᱠᱟᱛ',
    metric_trust_score: 'AI ᱯᱟᱹᱛᱭᱟᱹᱣ ᱥᱠᱳᱨ',
    metric_trust_sub: 'ᱥᱟᱹᱨᱤ ᱞᱮᱠᱷᱟ',
    filter_all: 'ᱡᱚᱛᱚ ᱨᱤᱯᱳᱨᱴ',
    filter_verified: 'ᱯᱟᱹᱛᱭᱟᱹᱣ ᱟᱠᱟᱱ',
    filter_critical: 'ᱟᱨᱟᱜ ᱦᱩᱥᱤᱭᱟᱹᱨ',
    filter_24h: 'ᱯᱟᱨᱚᱢᱮᱱ ᱒᱔ ᱴᱟᱲᱟᱝ',
    filter_label: 'ᱯᱷᱤᱞᱴᱟᱨ:',
    filter_active_label: 'ᱪᱟᱹᱞᱩ ᱯᱷᱤᱞᱴᱟᱨ:',
    filter_reset: 'ᱨᱤᱥᱮᱴ ᱢᱮ',
    map_title: 'ᱡᱟᱹᱛᱤᱭᱟᱹᱨᱤ ᱦᱚᱭ-ᱦᱤᱥᱤᱫ ᱨᱟᱰᱟᱨ',
    map_clusters: 'ᱠᱞᱟᱥᱴᱟᱨ',
    layer_dark: 'ᱧᱩᱛ ᱢᱮᱯ',
    layer_satellite: 'ᱥᱮᱴᱮᱞᱟᱭᱤᱴ',
    layer_verified: 'ᱯᱟᱹᱛᱭᱟᱹᱣ ᱨᱤᱯᱳᱨᱴ',
    feed_title: 'ᱞᱟᱭᱤᱵᱽ ᱦᱚᱭ-ᱦᱤᱥᱤᱫ ᱯᱷᱤᱰ',
    feed_subtitle: 'ᱱᱤᱛᱚᱜᱟᱜ ᱟᱯᱚᱛ ᱠᱷᱚᱵᱚᱨ',
    feed_verified: 'ᱯᱟᱹᱛᱭᱟᱹᱣ',
    feed_unverified: 'ᱵᱟᱝ ᱯᱟᱹᱛᱭᱟᱹᱣ',
    feed_critical: 'ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱜᱷᱚᱴᱚᱱ',
    feed_details: 'ᱵᱤᱵᱚᱨᱚᱱ ᱧᱮᱞ ᱢᱮ',
    feed_no_reports: 'ᱪᱮᱫ ᱨᱤᱯᱳᱨᱴ ᱵᱟᱹᱱᱩᱜ-ᱟ',
    alert_critical: 'ᱞᱟᱹᱠᱛᱤᱭᱟᱱ',
    alert_post_x: 'X ᱨᱮ ᱥᱮᱭᱟᱨ ᱢᱮ',
    footer_text: 'VARSHANET 2.0 ᱡᱟᱹᱛᱤᱭᱟᱹᱨᱤ ᱟᱯᱚᱛ ᱜᱚᱲᱚ ᱜᱽᱨᱤᱰ | v2.0.0',
    footer_crafted: 'ᱴᱤᱢ Tech_Tonic ᱦᱚᱛᱮᱛᱮ ᱛᱮᱭᱟᱨ',
    footer_sub: 'ᱚᱛ ᱥᱟᱬᱮᱥ ᱢᱚᱱᱛᱨᱟᱲᱚᱭ / IMD AI ᱦᱚᱭ-ᱦᱤᱥᱤᱫ ᱟᱨ ᱟᱯᱚᱛ ᱯᱨᱳᱴᱳᱠᱳᱞ'
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'varshanet_language';

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    try {
      const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY) as LanguageCode | null;
      if (stored && TRANSLATIONS[stored]) {
        return stored;
      }
    } catch {
      // ignore
    }
    return 'English';
  });

  const setLanguage = (newLang: LanguageCode) => {
    setLanguageState(newLang);
    try {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, newLang);
    } catch (err) {
      console.warn('Unable to persist language to localStorage', err);
    }
  };

  const t = (key: TranslationKey): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS['English'];
    return langDict[key] || TRANSLATIONS['English'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
