import React from 'react';
import { X, Printer, Download, FileCheck, Shield, MapPin, Building2, Users, AlertTriangle, Sparkles, Code2 } from 'lucide-react';
import { EventImpactResponse } from '../../types';

interface SitRepDossierModalProps {
  incident: EventImpactResponse | null;
  onClose: () => void;
}

export const SitRepDossierModal: React.FC<SitRepDossierModalProps> = ({ incident, onClose }) => {
  if (!incident) return null;

  const { impact_evaluation } = incident;
  const { scores, population_exposure, infrastructure, nowcast_trajectory, response_recommendations } = impact_evaluation;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    const md = `
# NATIONAL DISASTER SITUATION REPORT (SITREP)
**GOVERNMENT OF INDIA • NATIONAL WEATHER BIG DATA INTELLIGENCE GRID**
*Generated by VARSHANET 2.0 AI Impact Nowcasting Engine*

---
### 1. INCIDENT OVERVIEW
* **Incident Cluster ID:** ${incident.event_id}
* **Event Type:** ${incident.event_type} (${incident.severity} SEVERITY)
* **Location:** ${incident.city || 'Unknown'}, ${incident.state} (GPS: ${incident.latitude.toFixed(4)}°N, ${incident.longitude.toFixed(4)}°E)
* **Generated At:** ${new Date().toUTCString()}

---
### 2. CORE INTELLIGENCE METRICS
* **Evidence Confidence:** ${scores.evidence_confidence}%
* **Impact Risk Score:** ${scores.impact_risk} / 100
* **Response Priority:** ${scores.response_priority}
* **Escalation Probability:** ${(scores.escalation_probability * 100).toFixed(0)}%

---
### 3. DEMOGRAPHIC & VULNERABILITY EXPOSURE
* **Total Population in Buffer:** ${population_exposure.total_population_exposed.toLocaleString()} citizens
* **High-Risk Vulnerable Population:** ${population_exposure.vulnerable_population_exposed.toLocaleString()} (Infants, Elderly, Informal settlements)
* **Urban Population:** ${population_exposure.urban_population.toLocaleString()}
* **Population Density:** ${population_exposure.population_density_per_sqkm} persons/km²

---
### 4. CRITICAL INFRASTRUCTURE AT RISK
* **At-Risk Health Facilities:** ${infrastructure.hospitals_at_risk_count} Hospitals
* **Transport Arteries & Bridges:** ${infrastructure.bridges_roads_at_risk_count} Critical Assets
* **Infrastructure Risk Score:** ${infrastructure.infrastructure_risk_score} / 100

---
### 5. 3-HOUR IMPACT NOWCAST TRAJECTORY
${nowcast_trajectory.map(step => `* **${step.time_label}:** Risk ${step.predicted_risk_score}/100 [${step.predicted_severity}] (Conf: ${(step.confidence * 100).toFixed(0)}%)`).join('\n')}

---
### 6. OPERATIONAL ACTION DIRECTIVES (GOOGLE GEMINI & NDRF SOPs)
${response_recommendations.map(rec => `* **[${rec.priority_label}] ${rec.action}**\n  *Reason:* ${rec.reason}\n  *Affected Area:* ${rec.affected_area || 'General'}`).join('\n\n')}

---
*Official Communication of the State/National Emergency Operations Centre (SEOC/NEOC)*
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SITREP_${incident.event_id}_${incident.city || 'IND'}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadCAP = () => {
    const capXml = `<?xml version="1.0" encoding="UTF-8"?>
<alert xmlns="urn:oasis:names:tc:emergency:cap:1.2">
  <identifier>VARSHANET-CAP-${incident.event_id}-${Date.now()}</identifier>
  <sender>operations@varshanet.gov.in</sender>
  <sent>${new Date().toISOString()}</sent>
  <status>Actual</status>
  <msgType>Alert</msgType>
  <scope>Public</scope>
  <info>
    <category>Met</category>
    <event>${incident.event_type}</event>
    <urgency>${incident.severity === 'CRITICAL' ? 'Immediate' : 'Expected'}</urgency>
    <severity>${incident.severity}</severity>
    <certainty>Observed</certainty>
    <headline>OFFICIAL ${incident.severity} ALERT: ${incident.event_type} in ${incident.city}, ${incident.state}</headline>
    <description>${response_recommendations[0]?.reason || 'Severe weather and inundation risk detected by VARSHANET Big Data Grid.'}</description>
    <instruction>${response_recommendations.map(r => r.action).join('. ')}</instruction>
    <area>
      <areaDesc>${incident.city}, ${incident.state}, India</areaDesc>
      <circle>${incident.latitude.toFixed(4)},${incident.longitude.toFixed(4)},15.0</circle>
    </area>
  </info>
</alert>`;

    const blob = new Blob([capXml], { type: 'application/xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CAP_1.2_${incident.event_id}.xml`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-md animate-fade-in font-sans">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-3xl max-h-[92vh] overflow-y-auto shadow-2xl flex flex-col">
        {/* Header */}
        <div className="p-4 border-b border-slate-800 flex items-center justify-between sticky top-0 bg-slate-900/95 backdrop-blur-sm z-10">
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-xl bg-cyan-950 text-cyan-400 border border-cyan-800/40">
              <FileCheck className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">National Disaster Situation Report (SitRep)</h3>
              <p className="text-xs text-slate-400 font-mono">Dossier ID: SITREP-{incident.event_id}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleDownloadCAP}
              className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-amber-300 text-xs font-bold transition-all border border-slate-700 cursor-pointer"
              title="Download OASIS Common Alerting Protocol (CAP 1.2) XML payload"
            >
              <Code2 className="w-3.5 h-3.5" />
              <span>CAP 1.2 XML</span>
            </button>
            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold transition-all border border-slate-700 cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export .MD</span>
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-bold transition-all shadow-md cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print SitRep</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-xl hover:bg-slate-800 text-slate-400 hover:text-white transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Official Dossier Body */}
        <div className="p-6 space-y-6 text-slate-200 text-xs">
          {/* Government Official Header */}
          <div className="text-center pb-4 border-b border-slate-800 space-y-1">
            <h2 className="text-base font-extrabold text-white uppercase tracking-widest">
              National Disaster Management Authority (NDMA) & IMD
            </h2>
            <p className="text-[11px] text-cyan-400 font-mono">
              VARSHANET 2.0 AI Impact Nowcasting & Decision Support Grid
            </p>
            <p className="text-[10px] text-slate-500 font-mono">
              Timestamp: {new Date().toUTCString()} • CONFIDENTIAL OPERATIONAL DISPATCH
            </p>
          </div>

          {/* Incident Summary */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-3.5 rounded-xl bg-slate-950/80 border border-slate-800 font-mono">
            <div>
              <span className="text-[10px] text-slate-500 block uppercase">Event ID</span>
              <strong className="text-cyan-300">{incident.event_id}</strong>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 block uppercase">Category</span>
              <strong className="text-white">{incident.event_type}</strong>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 block uppercase">Location</span>
              <strong className="text-white">{incident.city}, {incident.state}</strong>
            </div>
            <div>
              <span className="text-[10px] text-slate-500 block uppercase">Response Priority</span>
              <strong className="text-rose-400">{scores.response_priority} (URGENT)</strong>
            </div>
          </div>

          {/* Core Metrics */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider">
              1. Quantitative Vulnerability & Impact Exposure
            </h4>
            <div className="grid grid-cols-3 gap-3">
              <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 text-center">
                <span className="text-[10px] text-slate-400 block">Total Exposed Population</span>
                <span className="text-lg font-bold font-mono text-white">
                  {population_exposure.total_population_exposed.toLocaleString()}
                </span>
              </div>
              <div className="p-3 rounded-xl bg-rose-950/20 border border-rose-800/40 text-center">
                <span className="text-[10px] text-rose-300 block">Vulnerable Count (Slums/Infants)</span>
                <span className="text-lg font-bold font-mono text-rose-400">
                  {population_exposure.vulnerable_population_exposed.toLocaleString()}
                </span>
              </div>
              <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 text-center">
                <span className="text-[10px] text-slate-400 block">At-Risk Hospitals / Health Units</span>
                <span className="text-lg font-bold font-mono text-amber-300">
                  {infrastructure.hospitals_at_risk_count} Facilities
                </span>
              </div>
            </div>
          </div>

          {/* 3-Hour Trajectory Table */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider">
              2. 3-Hour Impact Trajectory Nowcast
            </h4>
            <div className="overflow-x-auto rounded-xl border border-slate-800">
              <table className="w-full text-left text-xs font-mono">
                <thead className="bg-slate-950 text-slate-400 text-[10px] border-b border-slate-800">
                  <tr>
                    <th className="p-2.5">TIME OFFSET</th>
                    <th className="p-2.5">PROJECTED RISK</th>
                    <th className="p-2.5">SEVERITY</th>
                    <th className="p-2.5">EST. RAINFALL</th>
                    <th className="p-2.5">CONFIDENCE</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/60 bg-slate-950/40">
                  {nowcast_trajectory.map((step, idx) => (
                    <tr key={idx} className="hover:bg-slate-900/50">
                      <td className="p-2.5 font-bold text-white">{step.time_label}</td>
                      <td className="p-2.5 text-cyan-300">{step.predicted_risk_score} / 100</td>
                      <td className="p-2.5">
                        <span className={`px-1.5 py-0.5 rounded text-[10px] ${
                          step.predicted_severity === 'CRITICAL' ? 'bg-rose-950 text-rose-300' : 'bg-amber-950 text-amber-300'
                        }`}>
                          {step.predicted_severity}
                        </span>
                      </td>
                      <td className="p-2.5 text-slate-300">{step.predicted_rainfall_mm} mm</td>
                      <td className="p-2.5 text-emerald-400">{(step.confidence * 100).toFixed(0)}%</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Operational Action Directives */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider">
              3. Recommended Emergency Decisions (NDRF & Municipal Authority SOPs)
            </h4>
            <div className="space-y-2">
              {response_recommendations.map((rec, idx) => (
                <div key={idx} className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-mono font-bold px-1.5 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-800">
                      {rec.priority_label}
                    </span>
                    <strong className="text-white text-xs">{rec.action}</strong>
                  </div>
                  <p className="text-slate-400 text-[11px] font-sans">
                    <strong>Operational Reason:</strong> {rec.reason}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};